version: '3.7'

services:
  postgres:
    env_file:
      - ./envs/postgres.env

  integration:
    volumes:
      - ./integration/etc/supervisor/supervisord.conf:/etc/supervisor/supervisord.conf:ro
      - ./integration/integration.py:/usr/src/app/integration.py:ro
      - ./integration/susemanager.py:/usr/src/app/susemanager.py:ro
      - ./integration/jira_patch.py:/usr/src/app/jira_patch.py:ro
    env_file:
      - ./envs/jira.env
      - ./envs/postgres.env
      - ./envs/susemanager.env
    environment:
      FLASK_ENV: 'development'
